[package]
name = "ruspk"
version = "0.1.0"
authors = ["Sebastian Schmidt <publicarray@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Connect with the database
diesel = { version = "1.4", features = ["chrono"] }
# grap environemt vars
dotenv = "0.9.0"
# Lazy static initialization
lazy_static = "1.3"

# Rocket Web framework / server
rocket = "0.4"
rocket_contrib = { version = "0.4", default-features = false, features = ["json", "diesel_mysql_pool"] }

# Serialization/Deserialization
serde_json = "1"
serde = "1"
serde_derive = "1"
serde_with = "1.4"

#  Date and time
chrono = { version = "0.4", features = ["serde"] }
