[global.databases]
sqlite = { url = "db/database.sqlite" }
mysql = { url = "ruspk:ruspk@localhost/ruspk" }
limits = { forms = 83886080 } # 80Mb

[development]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"

[production]
address = "0.0.0.0"
port = 80
keep_alive = 5
log = "critical"
