
on: [push, pull_request]

name: Build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - postgres
          - mysql
          - sqlite

    steps:
    - uses: actions/checkout@v2

    - name: Stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --no-default-features --features ${{ matrix.features }} --verbose

    # - name: Run cargo bloat
    #   uses: orf/cargo-bloat-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     bloat_args: --release --no-default-features --features ${{ matrix.features }} --crates -p ruspk
    #     tree_args: --prefix-depth --features ${{ matrix.features }} --no-dev-dependencies -p ruspk
